### ISSUE TITLE
error when adding target to the command

### ISSUE THREAD

**Issue by cfrioux** [Aluriak/predator#2]
The following command works as expected 
```
python -m predator networks/ns_2.sbml
```
However, when adding the targets argument:
```
python -m predator networks/ns_2.sbml --targets d
```
I get the following error (on mac OSX and Ubuntu 18.04, python 3.7.6)
```
DEBUG args = Namespace(export=None, forbidden_seeds=[], forbidden_seeds_file=None, greedy=False, infile='networks/ns_2.sbml', info=False, intersection=False, no_prerun=False, no_topological_injection=False, pareto=False, pareto_full=False, scc_with_asp=False, seeds=[], seeds_file=None, semantic_injection=False, targets=['d'], targets_are_forbidden=False, targets_file=None, union=False, verbose=False, visualize=None, visualize_dag=None, visualize_without_reactions=None)
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cfrioux/wd/code/predator/predator/__main__.py", line 160, in <module>
    for idx, seeds in enumerate(predator.search_seeds(graph, seeds, forbidden_seeds, targets, enum_mode=enum_mode, graph_filename=graph_filename, explore_pareto=args.pareto, pareto_no_target_as_seeds=args.pareto_full, greedy=args.greedy, **supp_args), start=1):
  File "/Users/cfrioux/wd/code/predator/predator/predator.py", line 97, in search_seeds
    yield from func(graph_data, frozenset(start_seeds), frozenset(forbidden_seeds), frozenset(targets), graph_filename, enum_mode, **kwargs)
  File "/Users/cfrioux/wd/code/predator/predator/predator.py", line 324, in search_seeds_activate_targets_iterative
    for new_seeds, new_targets, new_fullfill in compute_hypothesis_from_scc(terminal, scc_data, sccs, rev_scc_dag, enum_mode, verbose=verbose):
  File "/Users/cfrioux/wd/code/predator/predator/predator.py", line 453, in _compute_hypothesis_from_scc__minimization
    yield from __compute_hypothesis_from_scc(models, scc_name, scc_encoding, sccs, rev_scc_dag, enum_mode, verbose)
  File "/Users/cfrioux/wd/code/predator/predator/predator.py", line 405, in __compute_hypothesis_from_scc
    _print('                NB MODEL:', len(models))
TypeError: object of type 'generator' has no len()
```
The ```--seeds a```option is working

**Comment by cfrioux** [comment]
Fixed with commit f77d6e30b693e9ec53ff20cacf61bff2222868b1
